### ISSUE TITLE
[docker] Question about migrating desktop instance to Docker instance.

### ISSUE THREAD

**Issue by imsorrywhat** [rmcrackan/Libation#1135]
I started Libation on macOS then saw there's an unsupported docker option. I did not finish downloading to leave some for testing with docker.

I'd prefer to run this in docker so I don't have to rely on manually opening Libation on an endpoint and have a question.

1. If I copy ```AccountsSettings.json```, ```Settings.json```, and ```LibationContext.db``` to the respective volumes, is this all that is needed to "resume" downloading from the stopping point on the macOS endpoint?

The goal is to avoid redownloading from the start again and potentially creating duplicates and having to deal with cleanup.

If it helps, below is my docker compose draft:

```
services:
  libation:
    container_name: libation
    restart: unless-stopped
    image: rmcrackan/libation:latest
    user: 1000:1000
    volumes:
      - /opt/docker/config/libation:/config
      - /opt/docker/config/libation/db:/db
      - /mnt/Audiobooks:/data
    environment:
      - SLEEP_TIME='12h' #Length of time to sleep before doing another scan/download. Set to -1 to run one.
      - LIBATION_BOOKS_DIR=/data #Folder where books will be saved
      - LIBATION_DB_DIR=/db  #Optional folder to load database from. If not mounted, will load database from LIBATION_CONFIG_DIR.
      - LIBATION_DB_FILE='LibationContext.db' #Name of database file to load. By default it will look for all .db files and load one if there is only one present.
```
