### ISSUE TITLE
Adhere to system font size.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [rmcrackan/Libation#760]
**Is your feature request related to a problem? Please describe.**

![Screenshot_20230925_221305](https://github.com/rmcrackan/Libation/assets/42837531/0410fd7f-1f30-4522-a70a-2ec09911028a)
![Screenshot_20230925_221351](https://github.com/rmcrackan/Libation/assets/42837531/b8245573-429c-4f0f-935d-f7a839e739d6)

**Describe the solution you'd like**

Adhere to the system font size configuration.

**Describe alternatives you've considered**

Provide application-specific font size preferences. However, this isn't an alternative *solution*.

**Comment by cbordeman** [comment]
Which OS do you run?  IS it the Winforms version or the Chardonnay (Avalonia) version of Libation?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/rmcrackan/Libation/issues/760#issuecomment-2408804966

@cbordeman, might I ask what GUI toolkit you use? I would rather file this upstream there, since you're correct that this shouldn't be your purview – on KDE and Windows, Qt takes care of it; on GNOME, GTK; etc.

**Comment by cbordeman** [comment]
@RokeJulianLockhart This project uses Avalonia.  Not sure what it uses under the cover.  Will have to see how it gets the font in each case...

**Comment by RokeJulianLockhart** [comment]
@cbordeman, in which case, https://github.com/AvaloniaUI/Avalonia/issues/15549#issue-2268028197 *may* be the upstream issue I've been looking for.

**Comment by cbordeman** [comment]
@RokeJulianLockhart What distro are you having an issue with?  And version?  And which desktop environment?  KDE?  Latest Plasma?

**Comment by RokeJulianLockhart** [comment]
@cbordeman, `kinfo` returns:

<blockQuote>

```YAML
      Operating System: Fedora Linux 40
    KDE Plasma Version: 6.2.0
KDE Frameworks Version: 6.7.0
            Qt Version: 6.7.2
        Kernel Version: 6.11.3-200.fc40.x86_64 (64-bit)
     Graphics Platform: Wayland
            Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
                Memory: 30.5 GiB of RAM
    Graphics Processor: AMD Radeon RX 5700
```

</blockQuote>
